services:
  nginx:  # リバースプロキシ
    image: nginx:latest
    ports:
      - "80:80"            #  外に出すのはここだけ
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

   # フロントエンド 
  frontend:
    build: ./frontend
    image: package_game_app-frontend:v1.0.0
    depends_on:
      - backend
    # 開発用コードと同期
    volumes:
      - ./frontend/public:/usr/share/nginx/html


  #バックエンド
  backend:
    build: ./backend
    image: package_game_app-backend:v1.0.0
    #.envファイルの読み込み
    env_file:
      - .env
    # MYSQLが起動するまで待機
    depends_on:
      db:
        condition: service_healthy
    # 開発用コードと同期
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules  # 上書き防止用（github上ではnode_modulesを管理下に置いてないため上書きされてしまう）

    # 開発用コマンドを実行
    command: npm run dev

  # データベース
  db:
    image: mysql:8.0
    #.envファイルの読み込み
    env_file: 
      - .env
    # MYSQLデータの永続化
    volumes:
       - mysql_data:/var/lib/mysql
       # 初期化用SQL実行
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    # ヘルスチェックの設定  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s


  keycloak-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
    command: start-dev
    depends_on:
      keycloak-db:
        condition: service_healthy
    ports:
      - "8080:8080"   # ← 最初はこれでOK（あとでnginxにまとめる)


# 永続化ボリュームを定義
volumes:
  mysql_data:  # MySQLデータの永続化
  keycloak_data:  # Keycloakデータの永続化
